---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5e95a53e5e73e60013e1d0ab/webhook/forestry
sections:
- type: heading
  label: heading
- type: document
  path: site-metadata.json
  label: Config
  templates:
  - config
- type: document
  path: src/data/footer.yml
  label: Footer Configuration
  templates:
  - footer
- type: document
  path: src/pages/index.md
  label: Home
  templates:
  - home
- type: directory
  path: src/pages
  label: page
  create: all
  match: "**/*"
  exclude: "{index.md,elements.md}"
  templates:
  - page
- type: document
  path: src/pages/elements.md
  label: Elements
  templates:
  - elements
- type: document
  path: src/data/menus.json
  label: Site Menus
  templates:
  - site_menus
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: npm run forestry:preview
